# base image
FROM alpine:3.5

# install python & pip
RUN apk add --update py2-pip

# install python modules
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt

#copy files req'd
COPY app.py /usr/src/app/
COPY templates/index.html /usr/src/app/templates/

# exposure port num
EXPOSE 5000

# run application
CMD ["python", "usr/src/app/app.py"]